import type { Item } from '../models/Item.ts';

const items: Item[] = [
  {
    id: 1,
    name: 'Coca-Cola',
    description: 'This is item 1',
    price: 10.0,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['gluten', 'nuts'],
  },
  {
    id: 2,
    name: 'Pastaga',
    description: 'This is item 2',
    price: 12.0,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: [],
  },
  {
    id: 3,
    name: 'Fanta',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 4,
    name: 'Pepsi',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 5,
    name: 'Sweppes',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 6,
    name: 'Vin blanc',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 7,
    name: 'Vin rouge',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 8,
    name: 'Vin rosé',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 9,
    name: 'Limonade',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 10,
    name: 'Limoncello',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 11,
    name: 'Pina colada',
    description: 'This is item 11',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 12,
    name: 'Whisky caca',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 13,
    name: 'shot de tequila',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 14,
    name: 'tekpaf',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 15,
    name: 'Orange pressée',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300',
    allergens: ['nuts'],
  },
  {
    id: 16,
    name: 'Sprite',
    description: 'This is item 3',
    price: 3.5,
    imageUrl: 'https://picsum.photos/400/300?random=3',
    allergens: ['nuts'],
  },
];

export default items;
